name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean compile package
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SimpleTP-JAR
        path: target/SimpleTP-*.jar
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean compile package
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: SimpleTP v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## SimpleTP v${{ steps.get_version.outputs.VERSION }}
          
          ### Features
          - Complete offline teleportation system
          - All teleportation commands (`/bring`, `/goto`, `/tpoff`, etc.)
          - Multiverse-Core integration for cross-world teleportation
          - Full permission system with granular control
          - Tab completion for all commands
          - Configurable messages and features
          - Persistent data storage for offline players
          
          ### Installation
          1. Download the JAR file below
          2. Place it in your server's `plugins` folder
          3. Restart your server
          4. Configure settings in `plugins/SimpleTP/config.yml`
          
          ### Commands
          - `/bring <player>` - Teleport a player to you
          - `/bringoff <player>` - Set offline teleport for a player to your location
          - `/bringall` - Teleport all online players to you
          - `/bringalloff` - Teleport all players (online + offline) to you
          - `/goto <player>` - Teleport to a player
          - `/gotooff <player>` - Teleport to an offline player's last location
          - `/tpoff <player1> <player2>` - Teleport player1 to player2 (supports offline)
          - `/simpletp [reload]` - Show plugin info or reload configuration
          
          ### Permissions
          - `SimpleTP.bring` - Allows teleporting players to you (default: op)
          - `SimpleTP.bringall` - Allows teleporting all players to you (default: op)
          - `SimpleTP.goto` - Allows teleporting to other players (default: op)
          - `SimpleTP.offline` - Allows offline teleportation features (default: op)
          - `SimpleTP.admin` - Allows administrative commands like reload (default: op)
          - `SimpleTP.*` - Gives access to all SimpleTP commands (default: op)
          
          ### Requirements
          - Minecraft Server 1.21.4
          - Java 21+
          - Optional: Multiverse-Core for enhanced cross-world support
        files: target/SimpleTP-*.jar
        draft: false
        prerelease: false 