name: Build Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: List target directory
      run: ls -la target/
      
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SimpleTP-plugin
        path: target/SimpleTP-*.jar
        if-no-files-found: error
        
    - name: Upload latest build
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: SimpleTP-latest
        path: target/SimpleTP-*.jar
        if-no-files-found: error 